version: "3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations orchestrator && python manage.py migrate && python manage.py runserver 0.0.0.0:8010"
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    depends_on:
      - redis

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A orchestration_project worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
